name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  "build":
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0

    - name: NPM install with caching
      uses: bahmutov/npm-install@v1.1.0

    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: "build-${{github.run_id}}"
        path: "./dist/client"